<?php
echo '<li><a href="../cardiovascular/aaa-prognosis-surveillance/index.php">Abdominal Aortic Aneurysm Prognosis and Surveillance</a></li>
<li><a href="../digestive-system/abdominal-exam/index.php">Abdominal Exam</a></li>
<li><a href="../digestive-system/abdominal-pain-history/index.php">Abdominal Pain History</a></li>
<li><a href="../skin/acne-plan/index.php">Acne Assessment/Plan</a></li>
<li><a href="../elder-care/barthel-adl/index.php">Activities of Daily Living (Barthel Index)</a></li>
<li><a href="../cardiovascular/grace-mortality-score/index.php">Acute Coronary Syndrome - GRACE Mortality Score</a></li>
<li><a href="../cardiovascular/rouan/index.php">Acute Coronary Syndrome - Rouan Decision Rule for Myocardial Infarction</a></li>
<li><a href="../mental-health/asrs-adhd/index.php">ADHD: Adult Self-Report Scale</a></li>
<li><a href="../mental-health/conners-history-adhd/index.php">ADHD: Connors\' Index History</a></li>
<li><a href="../mental-health/adhd-criteria/index.php">ADHD: DSM-IV Criteria for Attention Deficit Hyperactivity Disorder</a></li>
<li><a href="../elder-care/katz-adl/index.php">ADL - Index of Independence in Activities of Daily Living Calculator (Katz)</a></li>
<li><a href="../general/acute-adult-physical-exams/index.php">Adult Acute Physical Exams</a></li>
<li><a href="../general/adult-chronic-exams/index.php">Adult Chronic Disease Physical Exams</a></li>
<li><a href="../general/general-adult-physical-exams/index.php">General Adult Physical Exams</a></li>
<li><a href="../mental-health/cage-questionnaire/index.php">Alcohol - CAGE Questionnaire for Alcohol Abuse</a></li>
<li><a href="../mental-health/short-alcohol-withdrawal-scale/index.php">Alcohol - Short Withdrawal Scale</a></li>
<li><a href="../mental-health/audit/index.php">Alcohol Use Disorders Identification Test (AUDIT)</a></li>
<li><a href="../ear-nose-throat/allergic-rhinitis-plan/index.php">Allergic Rhinitis Assessment/Plan</a></li>
<li><a href="../ear-nose-throat/allergic-rhinitis-history/index.php">Allergic Rhinitis History</a></li>
<li><a href="../neurological/aloc-hx/index.php">Altered Level of Consciousness History</a></li>
<li><a href="../blood-lymph/anemia-evalulation/index.php">Anemia Evaluation</a></li>
<li><a href="../cardiovascular/singh-risk-score/index.php">Angioplasty Complication Risk Score - Singh</a></li>
<li><a href="../musculoskeletal/ottawa-ankle-and-foot-rules/index.php">Ankle and Foot Rules - Ottawa</a></li>
<li><a href="../musculoskeletal/ankle-sprain-plan/index.php">Ankle Sprain Assessment/Plan</a></li>
<li><a href="../cardiovascular/coumadin-calculator/index.php">Anticoagulation - Coumadin Adjustment Calculator</a></li>
<li><a href="../cardiovascular/outpatient-bleeding-risk-index-obri/index.php">Anticoagulation - Outpatient Bleeding Risk Index Calculator</a></li>
<li><a href="../mental-health/atypical-antipsychotic-monitor/index.php">Antipsychotic Medications, Atypical - Metabolic Monitoring</a></li>
<li><a href="../mental-health/zung-anxiety-scale/index.php">Anxiety Scale (Zung)</a></li>
<li><a href="../musculoskeletal/articular-vs-nonarticular/index.php">Arthritis Decision Tool - Articular Versus Nonarticular</a></li>
<li><a href="../musculoskeletal/inflammatory-vs-noninflammatory/index.php">Arthritis Decision Tool - Inflammatory Versus Noninflammatory</a></li>
<li><a href="../musculoskeletal/spondyloarthropathy/index.php">Arthritis Decision Tool - Spondyloarthropathy</a></li>
<li><a href="../musculoskeletal/arthritis-tests/index.php">Arthritis Decision Tool - Testing for Chronic Inflammatory Arthritides</a></li>
<li><a href="../musculoskeletal/inflammatory-vs-noninflammatory/index.php">Arthritis Decision Tool #1 - Chronic Inflammatory Polyarthritis</a></li>
<li><a href="../injury/assault-history/index.php">Assault History</a></li>
<li><a href="../respiratory/predicted-peak-flow/index.php">Asthma - Predicted Peak Expiratory Flow</a></li>
<li><a href="../respiratory/asthma-control/index.php">Asthma Control Decision Tool</a></li>
<li><a href="../respiratory/asthma-hx/index.php">Asthma History</a></li>
<li><a href="../respiratory/asthma-severity/index.php">Asthma Severity Classification</a></li>
<li><a href="../respiratory/asthma-control-questions/index.php">Asthma Symptom Control Questionnaire (Generic)</a></li>
<li><a href="../skin/atopic-dermatitis-plan/index.php">Atopic Dermatitis Assessment/Plan</a></li>
<li><a href="../cardiovascular/accp-stroke-risk-calculator/index.php">Atrial Fibrillation - ACCP Stroke Risk Calculator for Atrial Fibrillation</a></li>
<li><a href="../cardiovascular/chads2/index.php">Atrial Fibrillation - CHADS2 Calculator - Stroke Risk in Atrial Fibrillation</a></li>
<li><a href="../cardiovascular/chads2-vasc/index.php">Atrial Fibrillation - CHADS2-VASc Score - Stroke Risk in Atrial Fibrillation</a></li>
<li><a href="../cardiovascular/has-bled/index.php">Atrial Fibrillation - HAS-BLED Bleeding Risk in Atrial Fibrillation Anticoagulation</a></li>';
?>