<?php
echo '<li><a href="../musculoskeletal/dire-score/index.php">Pain - DIRE Score for Appropriate Opioid Use</a></li>
<li><a href="../musculoskeletal/opioid-risk-tool/index.php">Pain - Opioid Risk Tool</a></li>
<li><a href="../musculoskeletal/personal-care-plan-for-chronic-pain/index.php">Pain - Personal Care Plan for Chronic Pain</a></li>
<li><a href="../general/pain-hx/index.php">Pain History</a></li>
<li><a href="../general/pain-history/index.php">Pain History - Pain Scales</a></li>
<li><a href="../cardiovascular/palpitations-history/index.php">Palpitations History</a></li>
<li><a href="../mental-health/panic-severity/index.php">Panic Disorder - Severity Measure</a></li>
<li><a href="../child-health/pediatric-early-warning-score/index.php">Pediatric Early Warning Score</a></li>
<li><a href="../child-health/maintenance/index.php">Pediatric Health Maintenance Visit (Brief)</a></li>
<li><a href="../child-health/health-maintenance-visit/index.php">Pediatric Health Maintenance Visit (Expanded)</a></li>
<li><a href="../child-health/pediatric-physical-exam/index.php">Pediatric Physical Exam</a></li>
<li><a href="../child-health/acute-exams/index.php">Pediatric Acute Physical Exams</a></li>
<li><a href="../child-health/acute-exams/index.php">Pediatric Physical Exams, Acute</a></li>
<li><a href="../child-health/general-exams/index.php">Pediatric Physical Exams, General</a></li>
<li><a href="../neurological/peripheral-neuropathy-plan/index.php">Peripheral Neuropathy Plan</a></li>
<li><a href="../digestive-system/mannheim-peritonitis-index/index.php">Peritonitis - Mannheim Peritonitis Index</a></li>
<li><a href="../ear-nose-throat/adapted-centor-score/index.php">Pharyngitis - Adapted Centor Score for Strep Throat</a></li>
<li><a href="../ear-nose-throat/feverpain/index.php">FeverPAIN Score for Strep Throat</a></li>
<li><a href="../ear-nose-throat/pharyngitis-plan/index.php">Pharyngitis Assessment/Plan</a></li>
<li><a href="../ear-nose-throat/pharyngitis-history/index.php">Pharyngitis History</a></li>
<li><a href="../ear-nose-throat/sore-throat-complete-note/index.php">Pharyngitis Visit Complete Note</a></li>
<li><a href="../skin/pitted-keratolysis/index.php">Pitted Keratolysis Assessment/Plan</a></li>
<li><a href="../musculoskeletal/plantar-fasciitis-plan/index.php">Plantar Fasciitis Assessment/Plan</a></li>
<li><a href="../infectious/curb-65-score/index.php">Pneumonia - CURB-65 Score for Pneumonia</a></li>
<li><a href="../infectious/diehr-rule/index.php">Pneumonia - Diehr Rule to Diagnose Pneumonia</a></li>
<li><a href="../respiratory/pneumonia-severity-index/index.php">Pneumonia Severity Index</a></li>
<li><a href="../musculoskeletal/polymyalgia-rheumatica-healey/index.php">Polymyalgia Rheumatica Diagnostic Criteria – Healey</a></li>
<li><a href="../cardiovascular/pame-history/index.php">Pre-Anesthesia or Pre-Operative Medical Examination History</a></li>
<li><a href="../pregnancy/wheel-backwards/index.php">Pregnancy Dating Wheel – EDC (backwards)</a></li>
<li><a href="../pregnancy/wheel/index.php">Pregnancy Dating Wheel – LMP</a></li>
<li><a href="../pregnancy/preg-symptoms/index.php">Pregnancy Related Symptoms History</a></li>
<li><a href="../cardiovascular/preoperative-note/index.php">Preoperative Note</a></li>
<li><a href="../general/preorder/index.php">Preorder Coordination</a></li>
<li><a href="../general/procedural-pause/index.php">Procedural Pause</a></li>
<li><a href="../elder-care/4-year-prognostic-index/index.php">Prognostic - 4 Year Prognostic Index</a></li>
<li><a href="../men/prostate-symptom-score/index.php">Prostate Symptom Score</a></li>
<li><a href="../mental-health/bathe-technique/index.php">Psychosocial History - BATHE Technique</a></li>
<li><a href="../mental-health/ptsd-screen/index.php">PTSD - Post Traumatic Stress Disorder Screen</a></li>
<li><a href="../blood-lymph/wells-pe/index.php">Pulmonary Embolism - Wells Clinical Prediction Rule for Pulmonary Embolism</a></li>
<li><a href="../blood-lymph/perc/index.php">Pulmonary Embolism Rule out Criteria – PERC Rule</a></li>
<li><a href="../respiratory/pesi/index.php">Pulmonary Embolism Severity Index</a></li>
<li><a href="../skin/punch-plan/index.php">Punch Biopsy Assessment/Plan</a></li>';
?>