<?php
echo '<li><a href="../sample/boilerplate/index.php">Sample Boilerplate</a></li>
<li><a href="../sample/calculation/index.php">Sample Calculation</a></li>
<li><a href="../sample/check-boxes/index.php">Sample Check Box</a></li>
<li><a href="../sample/memo/index.php">Sample Comment</a></li>
<li><a href="../sample/conditional-comparison/index.php">Sample Conditional Comparison</a></li>
<li><a href="../sample/conditional/index.php">Sample Conditional Element</a></li>
<li><a href="../sample/date/index.php">Sample Date</a></li>
<li><a href="../sample/drop-down/index.php">Sample Drop Down</a></li>
<li><a href="../sample/exponent/index.php">Sample Exponent And Precision</a></li>
<li><a href="../sample/footnotes/index.php">Sample Footnotes</a></li>
<li><a href="../sample/html/index.php">Sample HTML</a></li>
<li><a href="../sample/interpreted-computation/index.php">Sample Interpreted Computation</a></li>
<li><a href="../sample/link/index.php">Sample Link</a></li>
<li><a href="../sample/mark/index.php">Sample Mark</a></li>
<li><a href="../sample/natural-log/index.php">Sample Natural Log and Log Base 10</a></li>
<li><a href="../sample/radio-buttons/index.php">Sample Radio Buttons</a></li>
<li><a href="../sample/simple-computations/index.php">Sample Simple Computations</a></li>
<li><a href="../sample/small-medium-large/index.php">Sample Small-Medium-Large Chooser</a></li>
<li><a href="../sample/stuart-smalley-quiz/index.php">Sample Stuart Smalley Quiz</a></li>
<li><a href="../sample/text-box/index.php">Sample Text Box</a></li>
<li><a href="../sample/textarea-with-linefeed/index.php">Sample Textarea with Linefeed</a></li>
<li><a href="../sample/two-lines-between-two-text-boxes/index.php">Sample Two Lines Between Two Text Boxes</a></li>
<li><a href="../sample/version-A-version-B/index.php">Sample Version A and Version B</a></li>
<li><a href="../skin/scabies-plan/index.php">Scabies Assessment/Plan</a></li>
<li><a href="../skin/scabies-hx/index.php">Scabies History</a></li>
<li><a href="../neurological/seizure-history/index.php">Seizure History</a></li>
<li><a href="../skin/shave-plan/index.php">Shave Biopsy Assessment/Plan</a></li>
<li><a href="../musculoskeletal/shoulder-exam/index.php">Shoulder Exam</a></li>
<li><a href="../musculoskeletal/shoulder-exam-detailed/index.php">Shoulder Exam (Detailed)</a></li>
<li><a href="../ear-nose-throat/sinusitis-exam/index.php">Sinusitis Exam</a></li>
<li><a href="../skin/tag-shave-plan/index.php">Skin Tag Shave Assessment/Plan</a></li>
<li><a href="../respiratory/epworth-sleepiness-scale/index.php">Sleep Apnea - Epworth Sleepiness Scale</a></li>
<li><a href="../respiratory/stop-bang/index.php">Sleep Apnea - STOP-BANG Questionnaire</a></li>
<li><a href="../mental-health/stages-of-change/index.php">Stage of Change Assessment</a></li>
<li><a href="../ear-nose-throat/adapted-centor-score/index.php">Strep Throat - Adapted Centor Score</a></li>
<li><a href="../ear-nose-throat/strep-throat-decision-tool/index.php">Strep Throat Decision Tool</a></li>
<li><a href="../neurological/nih-stroke-scale/index.php">Stroke - NIH Stroke Scale</a></li>
<li><a href="../neurological/abcd2/index.php">Stroke Risk - ABCD2 Score for CVA Risk after TIA</a></li>
<li><a href="../cardiovascular/accp-stroke-risk-calculator/index.php">Stroke Risk - ACCP Stroke Risk Calculator</a></li>
<li><a href="../eye/stye-plan/index.php">Stye Assessment/Plan</a></li>
<li><a href="../eye/stye-history/index.php">Stye History</a></li>
<li><a href="../neurological/ottawa-sah-rule/index.php">Subarachnoid Hemorrhage (SAH) - Ottawa Rule</a></li>
<li><a href="../mental-health/suicide-behaviors-questionnaire/index.php">Suicide Behaviors Questionnaire-Revised (SBQ-R)</a></li>
<li><a href="../cardiovascular/oesil-risk-score/index.php">Syncope - OESIL Risk Score for Syncope</a></li>
<li><a href="../cardiovascular/rose-risk-score/index.php">Syncope - ROSE Risk Score for Syncope</a></li>
<li><a href="../cardiovascular/syncope-prognosis-calculator/index.php">Syncope Prognosis Calculator</a></li>
<li><a href="../musculoskeletal/dx-sle/index.php">Systemic Lupus Erythematosus Diagnosis</a></li>
<li><a href="../musculoskeletal/2013-ssc-criteria/index.php">Systemic Sclerosis, Criteria for </a></li>';
?>