<?php
echo '<li><a href="../child-health/1-week-hx/index.php">1 Week History</a></li>
<li><a href="../child-health/1-week-plan/index.php">1 Week Plan</a></li>
<li><a href="../child-health/11-to-14-year-hx/index.php">11 to 14 Year History</a></li>
<li><a href="../child-health/11-to-18-year-plan/index.php">11 to 18 Year Plan</a></li>
<li><a href="../child-health/12-month-hx/index.php">12 Month History</a></li>
<li><a href="../child-health/12-month-plan/index.php">12 Month Plan</a></li>
<li><a href="../child-health/15-month-hx/index.php">15 Month History</a></li>
<li><a href="../child-health/15-month-plan/index.php">15 Month Plan</a></li>
<li><a href="../child-health/15-to-18-year-hx/index.php">15 to 18 Year History</a></li>
<li><a href="../child-health/2-month-hx/index.php">2 Month History</a></li>
<li><a href="../child-health/2-month-plan/index.php">2 Month Plan</a></li>
<li><a href="../child-health/2-to-6-year-prevention-hx/index.php">2 to 6 Year Prevention History</a></li>
<li><a href="../child-health/2-year-hx/index.php">2 Year History</a></li>
<li><a href="../child-health/2-year-plan/index.php">2 Year Plan</a></li>
<li><a href="../child-health/3-year-hx/index.php">3 Year History</a></li>
<li><a href="../child-health/3-year-plan/index.php">3 Year Plan</a></li>
<li><a href="../child-health/4-month-hx/index.php">4 Month History</a></li>
<li><a href="../child-health/4-month-plan/index.php">4 Month Plan</a></li>
<li><a href="../child-health/4-year-hx/index.php">4 Year History</a></li>
<li><a href="../child-health/4-year-plan/index.php">4 Year Plan</a></li>
<li><a href="../child-health/5-year-hx/index.php">5 Year History</a></li>
<li><a href="../child-health/5-year-plan/index.php">5 Year Plan</a></li>
<li><a href="../child-health/6-month-hx/index.php">6 Month History</a></li>
<li><a href="../child-health/6-month-plan/index.php">6 Month Plan</a></li>
<li><a href="../child-health/6-to-10-year-hx/index.php">6 to 10 Year History</a></li>
<li><a href="../child-health/6-to-10-year-plan/index.php">6 to 10 Year Plan</a></li>
<li><a href="../child-health/9-month-plan/index.php">9 Month Plan</a></li>';
?>