<?php
echo '<li><a href="../musculoskeletal/canadian-c-spine-rule/index.php">C-Spine, Canadian Rule</a></li>
<li><a href="../musculoskeletal/nexus-c-spine-rule/index.php">C-Spine, Nexus Rule</a></li>
<li><a href="../elder-care/capacity/index.php">Capacity - Checklist for Capacity to Make Treatment Decisions</a></li>
<li><a href="../cardiovascular/framingham/index.php">Cardiac Risk - ATP III Guidelines * Framingham Score for Cardiac Risk</a></li>
<li><a href="../cardiovascular/detskys-risk-index/index.php">Cardiac Risk - Detsky\'s Modified Cardiac Risk Index</a></li>
<li><a href="../cardiovascular/eagle-cardiac-risk-assessment/index.php">Cardiac Risk - Eagle Preoperative Cardiac Risk Assessment Tool</a></li>
<li><a href="../cardiovascular/fleisher-eagle-algorithm/index.php">Cardiac Risk - Fleisher-Eagle Algorithm</a></li>
<li><a href="../cardiovascular/global-risk-assessment-tool/index.php">Cardiac Risk - Global Risk Assessment Tool (2013 AHA/ACC Cardiac Calculator)</a></li>
<li><a href="../cardiovascular/lee-index/index.php">Cardiac Risk - Lee\'s Revised Cardiac Risk Index for Complication Following Surgery</a></li>
<li><a href="../cardiovascular/timi-risk-score/index.php">Cardiac Risk - TIMI Risk Score</a></li>
<li><a href="../cardiovascular/dm-cardiac-risk/index.php">Cardiac Risk in Diabetes Calculator (UKPDS)</a></li>
<li><a href="../cardiovascular/cardiovascular-examination/index.php">Cardiovascular Examination</a></li>
<li><a href="../cardiovascular/cardiovascular-exam-peds/index.php">Cardiovascular Examination (Pediatrics)</a></li>
<li><a href="../cardiovascular/cardio-exam/index.php">Cardiovascular Examination with Checkboxes</a></li>
<li><a href="../general/care-management/index.php">Care Management Documentation</a></li>
<li><a href="../elder-care/zarit-caregiver-burden/index.php">Caregiver - Zarit Caregiver Burden Interview</a></li>
<li><a href="../musculoskeletal/carpal-tunnel-exam/index.php">Carpal Tunnel Exam</a></li>
<li><a href="../musculoskeletal/casting-plan/index.php">Casting Assessment/Plan</a></li>
<li><a href="../cardiovascular/cardiac-chest-pain-decision-rule/index.php">Chest Pain - Bosner Chest Pain Decision Rule</a></li>
<li><a href="../cardiovascular/chest-pain-decision-rule/index.php">Chest Pain - Diamond and Forrester Chest Pain Decision Rule</a></li>
<li><a href="../cardiovascular/goldman-chest-pain/index.php">Chest Pain - Goldman Criteria for ICU Chest Pain Admission</a></li>
<li><a href="../cardiovascular/chest-pain-evaluation/index.php">Chest Pain Decision Tool</a></li>
<li><a href="../cardiovascular/chest-pain-history/index.php">Chest Pain History</a></li>
<li><a href="../cardiovascular/claudication-questionnaire/index.php">Claudication - Edinburgh Claudication Questionnaire</a></li>
<li><a href="../elder-care/cognitive-problems-history/index.php">Cognitive Problems History</a></li>
<li><a href="../elder-care/charlson-comorbidity-index/index.php">Comorbidity - Charlson Comorbidity Index</a></li>
<li><a href="../cardiovascular/jobst-prescription/index.php">Compression (Jobst) Stockings Assessment/Plan</a></li>
<li><a href="../general/concomitant-review-form/index.php">Concomitant Review Form</a></li>
<li><a href="../elder-care/confusion-assessment-method/index.php">Confusion - CAM-S Confusion Assessment Method</a></li>
<li><a href="../elder-care/confusion-plan/index.php">Confusion Assessment/Plan</a></li>
<li><a href="../elder-care/acute-confusion-plan/index.php">Confusion, Acute Assessment/Plan</a></li>
<li><a href="../women/initiating-contraception/index.php">Contraception - (Initiating) Contraception History</a></li>
<li><a href="../women/initiating-contraception-plan/index.php">Contraception - (Initiating) Contraception Plan</a></li>
<li><a href="../women/emergency-contraception-plan/index.php">Contraception - Emergency Contraception Assessment/Plan</a></li>
<li><a href="../women/initiating-contraception/index.php">Initiating Contraception History</a></li>
<li><a href="../women/switch-birth-control/index.php">Contraception - Switching Birth Control Methods</a></li>
<li><a href="../women/contraception-plan/index.php">Contraception Assessment/Plan</a></li>
<li><a href="../women/contraception-quick-start/index.php">Contraception Quick Start Algorithm</a></li>
<li><a href="../women/contraceptive-management/index.php">Contraceptive Management Visit</a></li>
<li><a href="../respiratory/bode-index/index.php">COPD Prognosis - BODE Index </a></li>
<li><a href="../respiratory/bap-65/index.php">COPD Risk Stratification - BAP-65 score</a></li>
<li><a href="../respiratory/copd-screening-tool/index.php">COPD Screening tool</a></li>
<li><a href="../cardiovascular/stress-testing-chd/index.php">Coronary Heart Disease - Stress Testing for Diagnosis of Coronary Heart Disease</a></li>
<li><a href="../respiratory/cough-exam/index.php">Cough Exam</a></li>
<li><a href="../respiratory/cough-history/index.php">Cough History</a></li>
<li><a href="../child-health/croup-plan/index.php">Croup Assessment/Plan</a></li>
<li><a href="../child-health/croup-history/index.php">Croup History</a></li>
';
?>